# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 03 May 2022 00:02:14 +0000
*               @ALL          1
*               @user         8

