<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: arman
 * Date: Tue, 03 May 2022 00:45:39 +0000
 */

$conf['title'] = 'Arman Tavakoli';
$conf['start'] = 'About me';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'arman';
$conf['proxy']['pass'] = '<b>YTgzZ0prTWIxcSFAJHNkOUpOQmQ=';
