# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 03 May 2022 00:02:14 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

arman:$1$HrFE4I5F$lfHVJzEdE69gaYvzOApVg.:Arman:arman@armantavakoli.ca:admin,user
